name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: [nightly-2023-04-16, stable]
        include:
        - toolchain: nightly-2023-04-16
          flags: -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
        - toolchain: stable
          flags:
        - os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
          target_name: check-extensions
        - os: windows-latest
          target: x86_64-pc-windows-msvc
          target_name: check-extensions.exe
        - os: macos-latest
          target: x86_64-apple-darwin
          target_name: check-extensions
    env:
      RUSTFLAGS:

    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
          toolchain: ${{ matrix.toolchain }}
          components: rust-src
    - name: Build
      run: cargo +${{ matrix.toolchain }} build ${{ matrix.flags }} --target ${{ matrix.target }} --release --verbose
    - name: Upload check-extensions artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target_name }} ${{ matrix.os }} ${{ matrix.toolchain }}
        path: target/${{ matrix.target }}/release/${{ matrix.target_name }}
    - name: Run tests
      run: cargo test --verbose
